GET https://api.agify.io?name=chris HTTP/1.1

###

POST http://127.0.0.1:8000/register_customer HTTP/1.1
Content-Type: application/json

{
    "VAT": "12345",
    "CustomerAccount": "4",
    "FullName": "'Afzan'",
    "Email": "'afzanhadile@ulb.be'",
    "Password": "'Hadile'"
}
###

POST http://127.0.0.1:8000/register_subscription HTTP/1.1
Content-Type: application/json

{
    "VAT": "12345",
    "SubscriptionN": "201",
    "SubscriptionInfo": "'type1'",
    "Price": "20"
}

###
POST http://127.0.0.1:8000/register_quote HTTP/1.1
Content-Type: application/json

{
    "VAT": "12345",
    "SubscriptionN": "200"
}

###
